
@startditaa

                            +------------+                +------------+
                            |            |   granted to   |            |
                            |    Role    +----------------+    User    |
                            |            | n            n |            |
                            +-----+------+                +------------+
                                n |
                                  |
                                  | includes
                                  |
                                n |
+------------+              +-----+------+
|            |   requires   |            |
| Operation  +--------------+ Privilege  |
|            | n          n |            |
+------------+              +------------+

@endditaa