@startuml

' https://plantuml.com/class-diagram
' https://plantuml.com/sequence-diagram
' https://plantuml-documentation.readthedocs.io/en/latest/formatting/all-skin-params.html
' https://plantuml-documentation.readthedocs.io/en/latest/formatting/all-skin-params.html#class
' https://plantuml.com/creole
' https://www.w3schools.com/colors/colors_names.asp

skinparam {
  'DefaultFontName Consolas
  DefaultFontName Monaco
  'DefaultFontName Lucida Console
  DefaultMonospacedFontName Consolas
  'DefaultFontStyle bold

  'BackgroundColor transparent
  BackgroundColor #fdfdfd
  PageMargin 10
  BoxPadding 100
  ParticipantPadding 20

  ArrowFontSize 16
  ArrowThickness 1
  MinClassWidth 75
  ClassFontStyle bold

  NoteBackgroundColor SeaShell
  NoteBorderColor transparent
  NoteShadowing false
}


skinparam Sequence{

  ParticipantFontName Consolas
  ArrowFontName Consolas

  DividerBorderThickness 1.5
  ReferenceBorderThickness 1.5
  MessageAlignment right

  ArrowColor DarkSlateGray
  ArrowThickness 1.3
  LifeLineBorderColor DarkSlateGray
  LifeLineBorderThickness 1.3

  ActorBorderColor DarkSlateGray
  ActorBackgroundColor GhostWhite
  ParticipantBorderColor DarkSlateGray
  ParticipantBorderThickness 1.5
  ParticipantBackgroundColor GhostWhite

  BoxBackgroundColor transparent
  BoxBorderColor transparent

  GroupBorderThickness 1.3
  GroupBorderColor DarkBlue
  GroupBodyBackgroundColor Azure
}

skinparam Group{
  BorderThickness 1.3
  BorderShadowing true
}

scale max 1536 width
hide Circle
hide Footbox
title Web3j Transaction Signing\n\n
'caption

participant client
participant RawTransactionManager as rawTxMgr
participant RawTransaction as rawTx
participant "rawTx::RawTransaction" as rawTx2
participant LegacyTransaction as legacyTx
participant "legacyTx::LegacyTransaction" as legacyTx2
participant TransactionEncoder as txEncoder
participant "signature::SignatureData" as signature
participant "signature3::SignatureData" as signature3
participant Sign as sign
participant Hash as hash
participant ECKeyPair as keypair
participant ECDSASigner as ecdsaSigner
participant "signature2::SignatureData" as signature2

url of rawTxMgr is [[https://github.com/web3j/web3j/blob/v4.8.8/core/src/main/java/org/web3j/tx/RawTransactionManager.java]]
url of rawTx is [[https://github.com/web3j/web3j/blob/v4.8.8/crypto/src/main/java/org/web3j/crypto/RawTransaction.java]]
url of signature is [[https://github.com/web3j/web3j/blob/v4.8.8/crypto/src/mai/java/org/web3j/crypto/Sign.java#L340]]
url of signature3 is [[https://github.com/web3j/web3j/blob/v4.8.8/crypto/src/mai/java/org/web3j/crypto/Sign.java#L340]]
url of sign is [[https://github.com/web3j/web3j/blob/v4.8.8/crypto/src/main/java/org/web3j/crypto/Sign.java]]
url of hash is [[https://github.com/web3j/web3j/blob/v4.8.8/utils/src/main/java/org/web3j/crypto/Hash.java]]
url of keypair is [[https://github.com/web3j/web3j/blob/v4.8.8/crypto/src/main/java/org/web3j/crypto/ECKeyPair.java]]
url of signature2 is [[https://github.com/web3j/web3j/blob/v4.8.8/crypto/src/mai/java/org/web3j/crypto/Sign.java#L340]]
url of ecdsaSigner is [[https://github.com/bcgit/bc-java/blob/b9891bd460a7a938cf642444a0164d5e5c94fba2/core/src/main/java/org/bouncycastle/crypto/signers/ECDSASigner.java]]

||100||

client -> rawTxMgr [[https://github.com/web3j/web3j/blob/v4.8.8/core/src/main/java/org/web3j/tx/RawTransactionManager.java#L111]] : sendTransaction(\n   //gasPrice//, \n   //gasLimit//, \n   //to//, \n   //data//, \n   //value//)
  rawTxMgr ++
  rawTxMgr -> rawTxMgr ++ : getNonce()
    rawTxMgr <-- rawTxMgr -- : <font:courier>return</font> nonce
  rawTxMgr -> rawTx ++ [[https://github.com/web3j/web3j/blob/v4.8.8/crypto/src/main/java/org/web3j/crypto/RawTransaction.java#L85]] : createTransaction(\n   nonce, \n   gasPrice, \n   gasLimit, \n   to, \n   value, \n   data)
    rawTx -> legacyTx ++ [[https://github.com/web3j/web3j/blob/v4.8.8/crypto/src/main/java/org/web3j/crypto/transaction/type/LegacyTransaction.java#L128]] : createTransaction(nonce, gasPrice, \ngasLimit, to, value, data)
      legacyTx -> legacyTx2 **
      rawTx <-- legacyTx --
    rawTx -> rawTx2 **
    rawTxMgr <-- rawTx -- : <font:courier>return</font> rawTx

  rawTxMgr -> rawTxMgr ++ [[https://github.com/web3j/web3j/blob/v4.8.8/core/src/main/java/org/web3j/tx/RawTransactionManager.java#L193]] : signAndSend(rawTx)
    rawTxMgr -> rawTxMgr ++ [[https://github.com/web3j/web3j/blob/v4.8.8/core/src/main/java/org/web3j/tx/RawTransactionManager.java#L180]] : sign(rawTx)
      rawTxMgr -> txEncoder ++ [[https://github.com/web3j/web3j/blob/v4.8.8/crypto/src/main/java/org/web3j/crypto/TransactionEncoder.java#L42]] : signMessage(rawTx, //chainId//, //credcredentials//)

        group 1st serialization
        txEncoder -> txEncoder ++ [[https://github.com/web3j/web3j/blob/v4.8.8/crypto/src/main/java/org/web3j/crypto/TransactionEncoder.java#L83]] : encode(rawTx, chainId)
          txEncoder -> signature **
          txEncoder -> txEncoder ++ [[https://github.com/web3j/web3j/blob/v4.8.8/crypto/src/main/java/org/web3j/crypto/TransactionEncoder.java#L94]] : encode(rawTx, signature)
            txEncoder -> txEncoder ++ [[https://github.com/web3j/web3j/blob/v4.8.8/crypto/src/main/java/org/web3j/crypto/TransactionEncoder.java#L113]] : asRlpValues(rawTx, \n   signature)
                txEncoder -> rawTx2 ++ [[https://github.com/web3j/web3j/blob/v4.8.8/crypto/src/main/java/org/web3j/crypto/RawTransaction.java#L147]] : getTransaction()
                  txEncoder <-- rawTx2 -- : legacyTx
                txEncoder -> legacyTx2 ++ [[https://github.com/web3j/web3j/blob/v4.8.8/crypto/src/main/java/org/web3j/crypto/transaction/type/LegacyTransaction.java#L70]] : asRlpValues(signature)
                  txEncoder <-- legacyTx2 -- :
              txEncoder --
            txEncoder --
          txEncoder <-- txEncoder -- : <font:courier>return serialized transaction</font>
        end

        group signing
        txEncoder -> sign ++ [[https://github.com/web3j/web3j/blob/v4.8.8/crypto/src/main/java/org/web3j/crypto/Sign.java#L73]] : signMessage(//message//, //keyPair//)
          sign -> sign ++ [[https://github.com/web3j/web3j/blob/v4.8.8/crypto/src/main/java/org/web3j/crypto/Sign.java#L77]] : signMessage(message, \n   keyPair, true)
            sign -> hash ++ [[https://github.com/web3j/web3j/blob/v4.8.8/utils/src/main/java/org/web3j/crypto/Hash.java#L81]] : sha3(message)
              hash -> hash ++ [[https://github.com/web3j/web3j/blob/v4.8.8/utils/src/main/java/org/web3j/crypto/Hash.java#L69]] : sha3(message, \n   //offset//, //length//)
                hash --
              sign <-- hash -- : <font:courier>return KECCAK hash</font> \n<font:courier>of serialized transaction</font>
            sign -> keypair ++ [[https://github.com/web3j/web3j/blob/v4.8.8/crypto/src/main/java/org/web3j/crypto/ECKeyPair.java#L52]] : sign(//hash//)
              keypair -> ecdsaSigner **
              keypair -> ecdsaSigner ++ [[https://github.com/bcgit/bc-java/blob/b9891bd460a7a938cf642444a0164d5e5c94fba2/core/src/main/java/org/bouncycastle/crypto/signers/ECDSASigner.java#L52]] : init(true, //privKey//)
                keypair <-- ecdsaSigner --
              keypair -> ecdsaSigner ++ [[https://github.com/bcgit/bc-java/blob/b9891bd460a7a938cf642444a0164d5e5c94fba2/core/src/main/java/org/bouncycastle/crypto/signers/ECDSASigner.java#L93]] : generateSignature(hash)
                keypair <-- ecdsaSigner -- : <font:courier>return ECDSA signature</font>
                note right
                Normalized(canonicalized) or not?  
                end note
              sign <-- keypair -- : <font:courier>return ECDSA signature</font>
            sign -> signature2 **
            sign <-- sign -- : <font:courier>return signature</font>
          txEncoder <-- sign -- : <font:courier>return signature</font>
        end

        txEncoder -> txEncoder ++ [[https://github.com/web3j/web3j/blob/v4.8.8/crypto/src/main/java/org/web3j/crypto/TransactionEncoder.java#L63]] : createEip155SignatureData(\n   signature, chainId)
          txEncoder -> signature3 **
          txEncoder <-- txEncoder -- : <font:courier>return EIP155 compatible signature</font>

        group 2nd serialization
        txEncoder -> txEncoder ++ [[https://github.com/web3j/web3j/blob/v4.8.8/crypto/src/main/java/org/web3j/crypto/TransactionEncoder.java#L94]] : encode(rawTx, signature3)
          txEncoder <-- txEncoder -- : <font:courier>return serialized signed transaction</font>
        end

        rawTxMgr <-- txEncoder -- : <font:courier>return serialized signed transaction</font>
      rawTxMgr <-- rawTxMgr -- : <font:courier>return serialized signed transaction</font>
    rawTxMgr <-- rawTxMgr --
  client <-- rawTxMgr --

||100||

@enduml
