
https://plantuml.com/sequence-diagram

@startuml
Hide Footbox
Title Credit Card Payment through Payment Gateway
Skinparam Sequence {
  GroupBorderThickness 1
  GroupBorderShadowing false
}

Actor "Donator:d2" as d2
Actor "Donator:d1" as d1
Participant Platform as p
Participant "Payme\nGateway" as pg
Participant "VAN\nProvider" as van
Participant "Credit Card\nIssuer:cc1" as cc1
Participant "Credit Card\nIssuer:cc2" as cc2
Participant "Account:acct-d1" as acct_d1
Participant "Account:acct-d2" as acct_d2
Participant "Account:acct-p1" as acct_p1
Participant "Account:acct-p2" as acct_p2

Group Donator 'd1' -> Project 'p1'
d1 -> p ++ : donate for project 1
Activate d1
d1 <<-- p -- : redirect to payment gateway

d1 -> pg ++ : request card payment
  pg -> van ++ : request card payment approval
    van -> cc1 ++ : request card payment approval
    Return approve
  Return approve
Return
Deactivate d1
p -> cc1 : request settlement
Activate p
Deactivate p
cc1 -> acct_d1 : withdraw
Activate cc1
Deactivate cc1
cc1 -> acct_p1 : deposit
Activate cc1
Deactivate cc1
End

|||
|||

Group Donator 'd1' -> Project 'p2'
d1 -> p ++ : donate for project 2
Activate d1
d1 <<-- p -- : redirect to payment gateway

d1 -> pg ++ : request card payment
  pg -> van ++ : request card payment approval
    van -> cc1 ++ : request card payment approval
    Return approve
  Return approve
Return
Deactivate d1

p -> cc1 : request settlement
Activate p
Deactivate p
cc1 -> acct_d1 : withdraw
Activate cc1
Deactivate cc1
cc1 -> acct_p2 : deposit
Activate cc1
Deactivate cc1
End

|||
|||

Group Donator 'd2' -> Project 'p2'
d2 -> p ++ : donate for project 2
Activate d2
d2 <<-- p -- : redirect to payment gateway

d2 -> pg ++ : request card payment
  pg -> van ++ : request card payment approval
    van -> cc2 ++ : request card payment approval
    Return approve
  Return approve
Return
Deactivate d2

p -> cc2 : request settlement
Activate p
Deactivate p
cc2 -> acct_d2 : withdraw
Activate cc2
Deactivate cc2
cc2 -> acct_p2 : deposit
Activate cc2
Deactivate cc2
End
@enduml